_wandb:
    value:
        cli_version: 0.21.0
        e:
            rjihvsgzdgvxkvdk91p3pj5deb2nuqzi:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "13958643712"
                args:
                    - --env-id
                    - InvertedPendulum-v4
                    - --total-timesteps
                    - "200000"
                    - --seed
                    - "3"
                    - --model-path
                    - models/ppo_seed3.zip
                    - --eval-freq
                    - "10000"
                    - --n-eval-episodes
                    - "10"
                    - --wandb-project
                    - counterfactual-agents
                    - --group
                    - ppo_training_5seeds
                    - --run-name
                    - ppo_train_seed3
                codePath: scripts/ppo_training_logging.py
                codePathLocal: scripts/ppo_training_logging.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "223812898816"
                email: t.kiss@campus.lmu.de
                executable: /Users/tommykiss/mujoco-py/venv/bin/python
                git:
                    commit: ec35684d841f96c726d0341d2358b697002be372
                    remote: git@github.com:MyyKii/Reasoning-in-RL.git
                host: Air-von-Tommy.fritz.box
                memory:
                    total: "17179869184"
                os: macOS-14.5-arm64-arm-64bit-Mach-O
                program: /Users/tommykiss/mujoco-py/scripts/ppo_training_logging.py
                python: CPython 3.13.1
                root: /Users/tommykiss/mujoco-py
                startedAt: "2026-01-06T23:46:29.094081Z"
                writerId: rjihvsgzdgvxkvdk91p3pj5deb2nuqzi
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.1
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
algo:
    value: PPO
env_id:
    value: InvertedPendulum-v4
eval_freq:
    value: 10000
n_eval_episodes:
    value: 10
seed:
    value: 3
total_timesteps:
    value: 200000
