_wandb:
    value:
        cli_version: 0.21.0
        e:
            wknvsrxnuznlb2rk31sdgjvgebmel2e0:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "12884901888"
                args:
                    - --env-id
                    - InvertedPendulum-v4
                    - --total-timesteps
                    - "100000"
                    - --seed
                    - "3"
                    - --model-path
                    - modcounterfactual-agentsels/ppo_seed3.zip
                    - --wandb-project
                    - counterfactual-agents
                    - --group
                    - ppo_reward_3
                    - --run-name
                    - ppo_seed3
                codePath: scripts/ppo_training_logging.py
                codePathLocal: scripts/ppo_training_logging.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "224445595648"
                email: t.kiss@campus.lmu.de
                executable: /Users/tommykiss/mujoco-py/venv/bin/python
                git:
                    commit: 459702cd047ae82bb3497e196e21f1431dfc9933
                    remote: git@github.com:MyyKii/Reasoning-in-RL.git
                host: Air-von-Tommy.fritz.box
                memory:
                    total: "17179869184"
                os: macOS-14.5-arm64-arm-64bit-Mach-O
                program: /Users/tommykiss/mujoco-py/scripts/ppo_training_logging.py
                python: CPython 3.13.1
                root: /Users/tommykiss/mujoco-py
                startedAt: "2026-01-18T22:58:14.056108Z"
                writerId: wknvsrxnuznlb2rk31sdgjvgebmel2e0
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.1
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
algo:
    value: PPO
env_id:
    value: InvertedPendulum-v4
eval_freq:
    value: 10000
n_eval_episodes:
    value: 10
seed:
    value: 3
total_timesteps:
    value: 100000
