_wandb:
    value:
        cli_version: 0.21.0
        e:
            4na18kqxc60790etur1i0idxtkvl5le5:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "15032385536"
                args:
                    - --epochs
                    - "51"
                    - --dagger-iter
                    - "1"
                    - --seed
                    - "2"
                    - --data
                    - data/AnfisTrainingSet_fromPPO1k_plus_dagger1_seed2_1k__2k.txt
                    - --kmeans-json
                    - data/kmeans_dagger0_1k_k3.json
                    - --bundle-out
                    - models/anfis_controller_1_51_epochs_seed2
                    - --wandb-project
                    - counterfactual-agents
                    - --group
                    - anfis_training_d1_e51_on_2k_seed2
                    - --run-name
                    - anfis_d1_seed2_51_epochs
                    - --tags
                    - dagger,iter1,kmeans,ppo,seed2
                codePath: scripts/anfis_model_fixed.py
                codePathLocal: scripts/anfis_model_fixed.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "224857427968"
                email: t.kiss@campus.lmu.de
                executable: /Users/tommykiss/mujoco-py/venv/bin/python
                git:
                    commit: 059356736454faa05c82ed5a87667a65bf523afc
                    remote: git@github.com:MyyKii/Reasoning-in-RL.git
                host: MacBook-Air-von-Tommy.local
                memory:
                    total: "17179869184"
                os: macOS-14.5-arm64-arm-64bit-Mach-O
                program: /Users/tommykiss/mujoco-py/scripts/anfis_model_fixed.py
                python: CPython 3.13.1
                root: /Users/tommykiss/mujoco-py
                startedAt: "2026-01-22T18:04:34.798102Z"
                writerId: 4na18kqxc60790etur1i0idxtkvl5le5
        m:
            - "1": train/epoch
              "6":
                - 3
              "7": []
            - "1": train/epoch_error
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch_rmse_vendor
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/proxy_reward_vendor
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/k
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/sum_t
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/eta
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "2": summary/*
              "6": []
              "7": []
            - "2": dataset/*
              "6": []
              "7": []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 61
            "4": 3.13.1
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
action_range:
    value: 6
bundle_out:
    value: models/anfis_controller_1_51_epochs_seed2
dagger_iter:
    value: 1
data:
    value: data/AnfisTrainingSet_fromPPO1k_plus_dagger1_seed2_1k__2k.txt
epochs:
    value: 51
group:
    value: anfis_training_d1_e51_on_2k_seed2
kmeans_json:
    value: data/kmeans_dagger0_1k_k3.json
run_name:
    value: anfis_d1_seed2_51_epochs
seed:
    value: 2
sigma_floor:
    value: 0.2
sigma_scale:
    value: 1.5
tags:
    value: dagger,iter1,kmeans,ppo,seed2
wandb_project:
    value: counterfactual-agents
