_wandb:
    value:
        cli_version: 0.21.0
        e:
            b1u9qx49856lh6kp9gfr9agw0bi5debv:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "13958643712"
                args:
                    - --data
                    - data/AnfisTrainingSet_PPO.txt
                    - --epochs
                    - "5"
                    - --seed
                    - "0"
                    - --kmeans-json
                    - data/kmeans_dagger0.json
                    - --bundle-out
                    - models/anfis_controller_dagger0
                    - --no-show
                    - --wandb-project
                    - counterfactual-agents
                    - --group
                    - dagger_seed0
                    - --run-name
                    - train_d0
                    - --tags
                    - seed0,dagger,iter0
                codePath: scripts/anfis_model.py
                codePathLocal: scripts/anfis_model.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "224581615616"
                email: t.kiss@campus.lmu.de
                executable: /Users/tommykiss/mujoco-py/venv/bin/python
                git:
                    commit: 40c6b2be1c919c2770cd8004943003aaf0aba345
                    remote: git@github.com:MyyKii/Reasoning-in-RL.git
                host: MacBook-Air-von-Tommy.local
                memory:
                    total: "17179869184"
                os: macOS-14.5-arm64-arm-64bit-Mach-O
                program: /Users/tommykiss/mujoco-py/scripts/anfis_model.py
                python: CPython 3.13.1
                root: /Users/tommykiss/mujoco-py
                startedAt: "2026-01-13T14:54:35.298730Z"
                writerId: b1u9qx49856lh6kp9gfr9agw0bi5debv
        m:
            - "1": dataset/step
              "6":
                - 3
              "7": []
            - "1": train/epoch
              "6":
                - 3
              "7": []
            - "1": summary/step
              "6":
                - 3
              "7": []
            - "2": dataset/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": summary/*
              "5": 3
              "6":
                - 1
              "7": []
        python_version: 3.13.1
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 7
                - 13
                - 15
                - 16
            "4": 3.13.1
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
bundle_out:
    value: models/anfis_controller_dagger0
data:
    value: data/AnfisTrainingSet_PPO.txt
epochs:
    value: 5
group:
    value: dagger_seed0
kmeans_json:
    value: data/kmeans_dagger0.json
no_show:
    value: true
run_name:
    value: train_d0
save_plots:
    value: null
seed:
    value: 0
tags:
    value: seed0,dagger,iter0
wandb_project:
    value: counterfactual-agents
